using System.Text.RegularExpressions;
using ManaBandi.Api.Data;
using ManaBandi.Api.Infrastructure;
using ManaBandi.Api.Models;
using ManaBandi.Api.Sms;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Npgsql;

namespace ManaBandi.Api.Services;

public class BookedForInput { public string? Name { get; set; } public string? Phone { get; set; } }

public class ParcelInput
{
    public string? ReceiverName { get; set; }
    public string? ReceiverPhone { get; set; }
    public string? Size { get; set; }
    public string? Payer { get; set; }
    public int? CodAmount { get; set; }
}

public class CreateRideRequest
{
    public string? ClientId { get; set; }
    public string? Service { get; set; }
    public PlaceDto? Pickup { get; set; }
    public PlaceDto? Drop { get; set; }
    public string? Payment { get; set; }
    public BookedForInput? BookedFor { get; set; }
    public ParcelInput? Parcel { get; set; }
}

public partial class RideService
{
    private readonly AppDbContext _db;
    private readonly AreaService _area;
    private readonly AccountService _accounts;
    private readonly ISmsSender _sms;
    private readonly IClock _clock;
    private readonly PublicOptions _pub;
    private readonly DispatchOptions _dispatch;
    private readonly ILogger<RideService> _log;

    public RideService(AppDbContext db, AreaService area, AccountService accounts, ISmsSender sms, IClock clock,
        IOptions<PublicOptions> pub, IOptions<DispatchOptions> dispatch, ILogger<RideService> log)
    {
        _db = db;
        _area = area;
        _accounts = accounts;
        _sms = sms;
        _clock = clock;
        _pub = pub.Value;
        _dispatch = dispatch.Value;
        _log = log;
    }

    [GeneratedRegex("^[A-Za-z0-9_-]{8,64}$")]
    private static partial Regex ClientIdRx();

    public object View(Ride r) => Views.ForRider(r, _pub.BaseUrl, _dispatch.AvgSpeedKmh);

    public IQueryable<Ride> WithDetails() =>
        _db.Rides.Include(r => r.Captain).ThenInclude(c => c!.User).Include(r => r.Rider).Include(r => r.Events);

    public async Task<Ride> LoadForRiderAsync(string rideId, string riderId, CancellationToken ct = default)
    {
        var r = await WithDetails().FirstOrDefaultAsync(r => r.Id == rideId, ct);
        // same 404 for "not yours" so ride ids cannot be probed
        if (r is null || r.RiderId != riderId) throw ApiException.NotFound("Ride not found");
        return r;
    }

    public async Task<(Ride ride, bool created)> CreateAsync(string riderId, CreateRideRequest req, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(req.ClientId) || !ClientIdRx().IsMatch(req.ClientId))
            throw ApiException.Validation("clientId must be a UUID generated by the app");
        var existing = await WithDetails().FirstOrDefaultAsync(r => r.RiderId == riderId && r.ClientId == req.ClientId, ct);
        if (existing != null) return (existing, false);

        var rider = await _db.Users.FirstOrDefaultAsync(u => u.Id == riderId, ct) ?? throw new ApiException(401, "unauthorized", "Login again");
        await _accounts.EnsureTermsAcceptedAsync(rider, ct);

        AreaService.ValidateService(req.Service);
        var service = req.Service!;
        var payment = req.Payment ?? "cash";
        if (payment is not ("cash" or "upi")) throw ApiException.Validation("payment must be cash or upi");

        string? size = null, payer = null, receiverName = null, receiverPhone = null;
        var cod = 0;
        if (service == "parcel")
        {
            var p = req.Parcel ?? throw ApiException.Validation("parcel details are required for a parcel booking");
            size = p.Size ?? "s";
            if (!AreaService.ParcelSizeBase.ContainsKey(size)) throw ApiException.Validation("parcel.size must be s, m or l");
            payer = p.Payer ?? "sender";
            if (payer is not ("sender" or "receiver")) throw ApiException.Validation("parcel.payer must be sender or receiver");
            receiverName = (p.ReceiverName ?? "").Trim();
            if (receiverName.Length is < 1 or > 100) throw ApiException.Validation("parcel.receiverName is required");
            receiverPhone = Phone.Normalize(p.ReceiverPhone) ?? throw ApiException.Validation("parcel.receiverPhone must be a valid mobile number");
            cod = p.CodAmount ?? 0;
            if (cod is < 0 or > 50000) throw ApiException.Validation("parcel.codAmount must be between 0 and 50000");
        }
        else if (req.Parcel != null) throw ApiException.Validation("parcel details are only for service=parcel");

        string? bfName = null, bfPhone = null;
        if (req.BookedFor != null && (req.BookedFor.Name != null || req.BookedFor.Phone != null))
        {
            bfName = (req.BookedFor.Name ?? "").Trim();
            if (bfName.Length is < 1 or > 100) throw ApiException.Validation("bookedFor.name is required");
            bfPhone = Phone.Normalize(req.BookedFor.Phone) ?? throw ApiException.Validation("bookedFor.phone must be a valid mobile number");
        }

        var active = await _db.Rides.Where(r => r.RiderId == riderId && RideStatus.NonTerminal.Contains(r.Status))
            .Select(r => r.Service).ToListAsync(ct);
        if (service != "parcel" && active.Any(s => s != "parcel"))
            throw new ApiException(409, "invalid_state", "You already have an active ride");
        if (active.Count >= 5) throw new ApiException(409, "invalid_state", "Too many active bookings");

        var q = await _area.QuoteAsync(service, req.Pickup!, req.Drop!, size, ct);
        var pickup = FillName(q.Town, req.Pickup!);
        var drop = FillName(q.Town, req.Drop!);
        var now = _clock.UtcNow;
        var ride = new Ride
        {
            Id = IdGen.New("r"),
            ClientId = req.ClientId!,
            RiderId = riderId,
            TownId = q.Town.Id,
            Service = service,
            Status = RideStatus.Searching,
            PickupLat = pickup.Lat, PickupLng = pickup.Lng, PickupName = pickup.Name!, PickupNameTe = pickup.NameTe, PickupLandmarkId = pickup.LandmarkId,
            DropLat = drop.Lat, DropLng = drop.Lng, DropName = drop.Name!, DropNameTe = drop.NameTe, DropLandmarkId = drop.LandmarkId,
            DistanceKm = q.DistanceKm,
            FareQuoted = q.Fare,
            Night = q.Night,
            Payment = payment,
            Otp = IdGen.Digits(4),
            BookedForName = bfName,
            BookedForPhone = bfPhone,
            ParcelSize = size,
            ParcelPayer = payer,
            ReceiverName = receiverName,
            ReceiverPhone = receiverPhone,
            CodAmount = cod,
            TrackToken = IdGen.Token(12),
            SearchStartedAt = now,
            CreatedAt = now,
            UpdatedAt = now,
        };
        if (service == "parcel")
        {
            do ride.DeliveryOtp = IdGen.Digits(4); while (ride.DeliveryOtp == ride.Otp);
        }
        ride.Events.Add(new RideEvent { RideId = ride.Id, Type = "requested", At = now, Lat = pickup.Lat, Lng = pickup.Lng, By = "rider" });
        _db.Rides.Add(ride);
        try
        {
            await _db.SaveChangesAsync(ct);
        }
        catch (DbUpdateException ex) when (ex.InnerException is PostgresException { SqlState: PostgresErrorCodes.UniqueViolation })
        {
            // the same clientId arrived twice at the same moment: return the ride that won
            _db.ChangeTracker.Clear();
            var again = await WithDetails().FirstOrDefaultAsync(r => r.RiderId == riderId && r.ClientId == req.ClientId, ct);
            if (again != null) return (again, false);
            throw;
        }
        ride.Rider = rider;
        return (ride, true);
    }

    private static PlaceDto FillName(Town t, PlaceDto p)
    {
        var named = AreaService.NamePlace(t, p.Lat, p.Lng);
        if (!string.IsNullOrWhiteSpace(p.LandmarkId) && t.Landmarks.FirstOrDefault(l => l.Id == p.LandmarkId) is { } lm)
            named = new PlaceDto { Lat = p.Lat, Lng = p.Lng, Name = lm.NameEn, NameTe = lm.NameTe, LandmarkId = lm.Id };
        return new PlaceDto
        {
            Lat = p.Lat,
            Lng = p.Lng,
            Name = string.IsNullOrWhiteSpace(p.Name) ? named.Name : p.Name.Trim(),
            NameTe = string.IsNullOrWhiteSpace(p.NameTe) ? named.NameTe : p.NameTe.Trim(),
            LandmarkId = named.LandmarkId,
        };
    }

    public async Task<Ride> CancelByRiderAsync(string riderId, string rideId, string? reason, CancellationToken ct = default)
    {
        var r = await LoadForRiderAsync(rideId, riderId, ct);
        if (r.Status is not (RideStatus.Searching or RideStatus.Accepted or RideStatus.Arrived))
            throw ApiException.InvalidState($"A ride that is {r.Status} cannot be cancelled");
        var now = _clock.UtcNow;
        var fee = r.AcceptedAt is { } acc && now - acc > TimeSpan.FromMinutes(2) ? 10 : 0;
        r.Status = RideStatus.Cancelled;
        r.CancelledAt = now;
        r.EndedAt = now;
        r.UpdatedAt = now;
        r.CancelledBy = "rider";
        r.CancelReason = Trim(reason, 200);
        r.CancelFee = fee;
        r.Events.Add(new RideEvent { RideId = r.Id, Type = "cancelled", At = now, By = "rider", Reason = r.CancelReason, Fee = fee > 0 ? fee : null, CaptainId = r.CaptainId });
        await _db.SaveChangesAsync(ct);
        await _db.Offers.Where(o => o.RideId == r.Id && o.Status == OfferStatus.Pending)
            .ExecuteUpdateAsync(s => s.SetProperty(o => o.Status, OfferStatus.Cancelled).SetProperty(o => o.RespondedAt, now), ct);
        return r;
    }

    public async Task RateAsync(string riderId, string rideId, int stars, int tip, CancellationToken ct = default)
    {
        if (stars is < 1 or > 5) throw ApiException.Validation("stars must be 1 to 5");
        if (tip is not (0 or 10 or 20)) throw ApiException.Validation("tip must be 0, 10 or 20");
        var r = await LoadForRiderAsync(rideId, riderId, ct);
        if (r.Status != RideStatus.Finished) throw ApiException.InvalidState("Only finished rides can be rated");
        if (r.Rating != null) throw ApiException.InvalidState("This ride is already rated");
        r.Rating = stars;
        r.Tip = tip;
        r.UpdatedAt = _clock.UtcNow;
        await _db.SaveChangesAsync(ct);
        if (r.CaptainId != null)
        {
            var agg = await _db.Rides.Where(x => x.CaptainId == r.CaptainId && x.Rating != null)
                .GroupBy(x => 1).Select(g => new { avg = g.Average(x => (double)x.Rating!), n = g.Count() }).FirstAsync(ct);
            await _db.Captains.Where(c => c.Id == r.CaptainId).ExecuteUpdateAsync(s => s
                .SetProperty(c => c.Rating, Math.Round(agg.avg, 1))
                .SetProperty(c => c.RatingCount, agg.n), ct);
        }
    }

    public async Task SosAsync(string userId, string role, string rideId, double? lat, double? lng, CancellationToken ct = default)
    {
        var r = await WithDetails().FirstOrDefaultAsync(x => x.Id == rideId, ct) ?? throw ApiException.NotFound("Ride not found");
        var byCaptain = role == Roles.Captain;
        if (byCaptain ? r.Captain?.UserId != userId : r.RiderId != userId) throw ApiException.NotFound("Ride not found");
        if (lat is { } la && lng is { } lo && !Geo.ValidLatLng(la, lo)) throw ApiException.Validation("Invalid location");
        var now = _clock.UtcNow;
        var sos = new SosEvent
        {
            Id = IdGen.New("sos"), RideId = r.Id, TownId = r.TownId, By = byCaptain ? "captain" : "rider",
            UserId = userId, Lat = lat, Lng = lng, At = now,
        };
        _db.SosEvents.Add(sos);
        _db.RideEvents.Add(new RideEvent { RideId = r.Id, Type = "sos", At = now, Lat = lat, Lng = lng, By = sos.By });
        await _db.SaveChangesAsync(ct);
        _log.LogWarning("SOS {SosId} on ride {RideId} in {Town} by {By}", sos.Id, r.Id, r.TownId, sos.By);

        var user = byCaptain ? r.Captain?.User : r.Rider;
        if (!string.IsNullOrEmpty(user?.TrustedContactPhone))
        {
            var link = $"{_pub.BaseUrl.TrimEnd('/')}/t/{r.TrackToken}";
            var name = string.IsNullOrWhiteSpace(user.Name) ? "Your contact" : user.Name;
            try
            {
                await _sms.SendMessageAsync(user.TrustedContactPhone, "sos_trusted_contact",
                    new Dictionary<string, string> { ["name"] = name, ["link"] = link },
                    $"{name} pressed SOS in Mana Bandi. Location: {link}", ct);
                sos.ContactNotified = true;
                await _db.SaveChangesAsync(ct);
            }
            catch (Exception ex)
            {
                _log.LogError(ex, "SOS SMS to trusted contact failed for {SosId}", sos.Id);
            }
        }
    }

    public static string? Trim(string? s, int max) => string.IsNullOrWhiteSpace(s) ? null : s.Trim().Length > max ? s.Trim()[..max] : s.Trim();
}
